#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LeftClawPot,    sensorPotentiometer)
#pragma config(Sensor, in2,    RightClawPot,   sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  liftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  lEnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rEnc,           sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  RightBackDriveEnc, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LeftBackDriveEnc, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  LeftMiddleLiftEnc, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  RightMiddleLiftEnc, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LeftClaw,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           TopLift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftBottomLift, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port4,           LeftTopDrive,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RightTopDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightBottomDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           LeftBottomDrive, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port8,           RightBottomLift, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           MiddleLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightClaw,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#define I2C_TICKS_PER_REV_SPEED 392

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "slew_rate.c"
#include "functions.c"
#include "gps.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{

	if( nVexRCReceiveState && vrCompetitionSwitch ) //Check if connected to comp switch
	{

		SensorValue(gyro) = 0;

		wait1Msec(1500); //give time for gyro to init

	}

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	startTask( clawHold );
	startTask( liftHold );
	//startTask( MotorSlewRateTask );
	startTask( drivePControl );

	doDriveP = true;
	doClawHold = true;
	doLiftHold = true;

	liftTarget = 900;
	clawPos( OPEN );

	moveDriveTarget( 1750 );
	waitUntilComplete();

	wait1Msec( 200 );

	liftTarget = 1000;

	wait1Msec( 500 );

	moveDriveTarget( -900 );
	//wait1Msec( 200 );
	waitUntilComplete();

	wait1Msec( 750 );

	setGyroTarget( -900 );
	wait1Msec( 200 );
	waitUntilComplete();

	wait1Msec( 200 );

	setDriveTarget();

	wait1Msec( 500 );

	moveDriveTarget( 1200 );
	waitUntilComplete();

	wait1Msec( 200 );

	setGyroTarget( 0 );
	wait1Msec( 200 );
	waitUntilComplete();

	wait1Msec( 200 );

	liftTarget = 800;
	lClawTarget = 610;
	rClawTarget = 1300;

	wait1Msec( 200 );

	setDriveTarget();

	wait1Msec( 500 );

	moveDriveTarget( 300 );
	waitUntilComplete();
	wait1Msec( 500 );

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  startTask( clawHold );
  startTask( liftHold );

  while (true)
  {

		driverClaw( ( vexRT[Btn6DXmtr2]*-127 + vexRT[Btn6UXmtr2]*127 + 10 ) );
  	lift( vexRT[Btn5UXmtr2]*127 + vexRT[Btn5DXmtr2]*-50 + vexRT[Btn7DXmtr2]*-127 + 10 );
		driverDrive( trueSpeed( vexRT[Ch3] ), trueSpeed( vexRT[Ch2] ) );

  	wait1Msec( 25 );

  }
}
