#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           L1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           R1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           L2,            tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port4,           R2,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port5,           L,             tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port6,           R,             tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port7,           L3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           L4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          R4,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#define L_DRIVE_ENC I2C_1
#define R_DRIVE_ENC I2C_2
#define L_LIFT_ENC I2C_4
#define R_LIFT_ENC I2C_3
#define PID_INTEGRAL_LIMIT 40
#define RECORD_DELAY 200
#define REPLAY_DELAY 200
#define POINT_LEFT 5
#define POINT_RIGHT 6

#include "Vex_Competition_Includes.c"
//All of our libraries
#include "ported_functions.c"
#include "functions.c"
#include "auton.c"
#include "slew_rate.c"

void pre_auton()
{

	LCDInit();
	chooseAuton();

}

task autonomous()
{

	runLCDAuton();

}
string hello = "woo";
task usercontrol()
{

	startTask(MotorSlewRateTask);

	nMotorEncoder[L] = 0;
	nMotorEncoder[R] = 0;
	nMotorEncoder[L2] = 0;
	nMotorEncoder[R2] = 0;

	while( true )
	{

		drive( trueSpeed( vexRT( Ch3 ) ), trueSpeed( vexRT( Ch2 ) ) );

  	lift((vexRT(Btn5UXmtr2)*117 + 10 - vexRT( Btn5DXmtr2 ) * 70 - vexRT( Btn6DXmtr2 ) * 137 /*Main Controller + vexRT( Btn5U ) * 117 + 10 - vexRT( Btn5D ) * 70 - vexRT( Btn6D ) * 137 */));

	}

}
