#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           L1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           R1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           L2,            tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port4,           R2,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port5,           L,             tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port6,           R,             tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port7,           L3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           L4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          R4,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#define TICKS_PER 627.2
#define GYRO 3
#define LEFTENC I2C_1
#define RIGHTENC I2C_2
#define LLIFTENC I2C_4
#define RLIFTENC I2C_3
#define LEFT 0
#define RIGHT 1

int choice = 0;

//Main competition background code...do not modify!
#include "BNSLibrary-master/BNSLib.h"
#include "Vex_Competition_Includes.c"
#include "GyroLib.c"
#include "GPS.c"
#include "Mario_Functions.c"
#include "rerun_functions.c"


void pre_auton()
{

	BNS();

	GyroInit( GYRO );

	SensorValue( I2C_3 ) = 0;
	SensorValue( I2C_4 ) = 0;

	LCDInit();

	chooseAuton();

}



task autonomous()
{

	SensorValue( I2C_3 ) = 0;
	SensorValue( I2C_4 ) = 0;

	runLCDAuton();

	//wait1Msec( 1000 );

	//auton3( 300 );

}


task usercontrol()
{

	startTask(Record);

  while (true)
  {

  	gps();

  	GPSDisplay();

  	drive( trueSpeed( vexRT( Ch3 ) ), trueSpeed( vexRT( Ch2 ) ) );

  	lift((vexRT(Btn5UXmtr2)*117 + 10 - vexRT( Btn5DXmtr2 ) * 70 - vexRT( Btn6DXmtr2 ) * 137 ) );

  	if (vexRT(Btn7L))
  	{

  		recording = true;

  	}

  	if (vexRT(Btn7R))
  	{

  		recording = false;

  	}

  	//liftToAngle( ( vexRT(Btn8LXmtr2)*10 + vexRT(Btn8UXmtr2)*30 + vexRT(Btn8RXmtr2)*70 + vexRT(Btn8DXmtr2)*100) );

  }

}
